### ISSUE TITLE
Request for migrating project to godot4.0

### ISSUE THREAD

**Issue by HackLinjiuyue** [DmitriySalnikov/godot_qoi#5]

**Comment by DmitriySalnikov** [comment]
The main part of the wrapper now seems to work in Godot 4
(all asserts are processed as before and even the icon goes through the whole cycle - save qoi -> read qoi -> encode into qoi array -> decode qoi array -> display 🙂)
![image](https://user-images.githubusercontent.com/7782218/203794174-b62e7b6b-1bfc-43a9-a51d-5b65991e6a96.png)

Now I'm thinking how to implement the importer.
Most likely I will use the ability to import QOI as CompressedTexture2D (the same way as webp, jpeg, png) (if I remember correctly, and there was such an ability...). But in this case, the decoding speed of imported images will be equal to the speed of webp if you do not use VRAM compression and will be much faster than webp and qoi if you use VRAM compression.
Previously I used my own storage format for imported QOI (original QOI file + metadata)

**Comment by DmitriySalnikov** [comment]
![image](https://user-images.githubusercontent.com/7782218/203834733-2bdd06c4-d1b6-413e-94da-cd5c379e9376.png)
A few more checks and I will publish it

**Comment by HackLinjiuyue** [comment]
> 

Thanks very much for your effort!!!

**Comment by DmitriySalnikov** [comment]
Most likely this version should already work on win/linux/mac 57ea46360806b2efa41ee5ab296ca1595695c96b

Now I'm thinking how to add android support correctly (if possible)

**Comment by HackLinjiuyue** [comment]
> Most likely this version should already work on win/linux/mac [57ea463](https://github.com/DmitriySalnikov/godot_qoi/commit/57ea46360806b2efa41ee5ab296ca1595695c96b)
> 
> Now I'm thinking how to add android support correctly (if possible)

You did a good job bro! Looking forward to seeing your porting progress soon!

**Comment by DmitriySalnikov** [comment]
Updated .gdextension file 3042a3fcf547b6521dfc1d4738dedab990ca067f

But now it is impossible to export the projects without this fix: https://github.com/godotengine/godot/pull/67906

**Comment by DmitriySalnikov** [comment]
I found a way to export the project in beta6. 1c7e2d12aa18fe31d705e98b152e817609c91294

I think the porting is mostly complete. But it is impossible to run this library on Android.

**Comment by HackLinjiuyue** [comment]
> I found a way to export the project in beta6. [1c7e2d1](https://github.com/DmitriySalnikov/godot_qoi/commit/1c7e2d12aa18fe31d705e98b152e817609c91294)
> 
> I think the porting is mostly complete. But it is impossible to run this library on Android.

Are there any restrictions that Android has which led to this issue?
